[package]
name = "leptos-alternate-view"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true


[dependencies]

proc-macro2 = "*"
quote = "*"
syn = { version = "2", features = ["extra-traits", "full", "parsing"] }

[dev-dependencies]
pretty_assertions = "1"
prettyplease = "0.2"
