[package]
name = "cushy-rodio"
version = "0.1.0"
edition = "2021"

[dependencies]

# cushy = { git = "https://github.com/khonsulabs/cushy", rev = "f08b7064ec5effb93eb92bea5a3e0f9e71f13544" }
cushy = "0.4.0"
rodio = "0.19.0"

[profile.dev.package."*"]
opt-level = 2
